<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <AssemblyName>com.github.teamxiaolan.dawnlib.daybreak</AssemblyName>
        <Product>DawnLib.Daybreak</Product>
    </PropertyGroup>

    <!-- Project Properties -->
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RootNamespace>Daybreak</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    
    <!-- Enable Nullable for better IDE null-checking -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <!-- Embed Debug Symbols for Easier Debugging -->
    <PropertyGroup>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <!--
        Trim the project path to prevent players from potentially
        viewing Private Information in stack traces.
        -->
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    </PropertyGroup>
	
    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="5.4.21"/>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.1" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="MMHOOK_BepInEx" Publicize="true">
        <PrivateAssets>all</PrivateAssets>
          <HintPath>deps\MMHOOK_BepInEx.dll</HintPath>
      </Reference>
    </ItemGroup>

    <Target Name="PublishThunderstore">
    </Target>
</Project>
