using System.Runtime.CompilerServices;
using BepInEx.Bootstrap;
using BepInEx.Configuration;
using Dawn.Utils;
using Dusk;
using LethalConfig;
using LethalConfig.AutoConfig;
using LethalConfig.ConfigItems;
using LethalConfig.Mods;

namespace Dawn.Internal;
static class DuskLethalConfigCompat
{
    internal const string VERSION = "1.4.6";
    public static bool Enabled => Chainloader.PluginInfos.ContainsKey(PluginInfo.Guid) && DawnConfig.LethalConfigCompatibility.Value.ShouldRunCompatibility(VERSION, Chainloader.PluginInfos[PluginInfo.Guid].Metadata.Version);

    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    public static void CreateLethalConfigMod(DuskMod duskMod)
    {
        ModInfo modInformation = new ModInfo()
        {
            Name = duskMod.ModInformation.ModName,
            Guid = $"com.local.{duskMod.ModInformation.ModName}.{duskMod.ModInformation.AuthorName}",
            Version = duskMod.ModInformation.Version,
            Description = duskMod.ModInformation.ModDescription,
            Icon = duskMod.ModInformation.ModIcon
        };
        Mod mod = new(modInformation);
        LethalConfigManager.Mods.Add(modInformation.Guid, mod);

        foreach (ConfigEntryBase configEntry in duskMod.ConfigEntries)
        {
            Debuggers.LethalConfig?.Log($"No-Code DuskMod | Generating config item for {configEntry.Definition.Section}.{configEntry.Definition.Key} with type {configEntry.SettingType} and value {configEntry.BoxedValue}");
            BaseConfigItem? baseConfigItem = AutoConfigGenerator.GenerateConfigForEntry(configEntry);
            if (baseConfigItem != null)
            {
                baseConfigItem.IsAutoGenerated = true;
                baseConfigItem.Owner = mod;
                mod.ConfigItems.Add(baseConfigItem);
            }
        }
    }
}